#!/bin/bash

# 获取 mode 变量
set -x
echo $COMMUNITY > /config/community
# 判断 mode
if [ "$MODE" = "supernode" ]; then
    /n2n/supernode -f -v -c /config/community -p $SUP_PORT $SUP_OPTION
# port default 7654
elif [ "$MODE" = "edge" ]; then
    /n2n/edge  -f -v -c $COMMUNITY  -a $N2N_IP -k $N2N_KEY -m $N2N_MAC -l  $N2N_SUP $N2N_OPTION

elif [ "$MODE" = "both" ]; then
    /n2n/supernode -f -v -c /config/community -p $SUP_PORT $SUP_OPTION &
   /n2n/edge  -f -v -c $COMMUNITY  -a $N2N_IP -k $N2N_KEY -m $N2N_MAC -l  $N2N_SUP $N2N_OPTION 
else
   echo  "MODE can only be edge/supernode/both "
    exit 0
fi
if [ "$SOCAT_MODE" = "ENABLE" ]; then
    socat $SOCAT_MONITOR,reuseaddr,fork $SOCAT_FORK

fi


set +x
